Add AbstractClassAssert#isPrimitive() and AbstractClassAssert#isNotPrimitive()
assertj/assertj pull request #2722
Opened 2022-07-29 21:53 UTC by ManuelG28

#### Check List:
* Fixes #2717
* Unit tests: YES 
* Javadoc with a code example (on API only): YES 
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)

2022-07-31 04:31 UTC, joel-costigliola requested changes
Thanks @ManuelG28, first round of code review done. PR looks good, just some minor/improvements comments to address.

2022-07-31 04:31 UTC, joel-costigliola commented on assertj-core/src/main/java/org/assertj/core/api/AbstractClassAssert.java
> +   * </code></pre>
join lines and remove double `;`

2022-07-31 04:31 UTC, joel-costigliola commented on assertj-core/src/main/java/org/assertj/core/api/AbstractClassAssert.java
> +   * assertThat(chart.class).isNotPrimitive();
you need to close the tags with `</code></pre>` in the same line.
tip: generate javadoc with `mvn javadoc:javadoc` and see if it looks good

2022-07-31 04:31 UTC, joel-costigliola commented on assertj-core/src/test/java/org/assertj/core/api/classes/ClassAssert_isNotPrimitive_Test.java
> + *  * @author Manuel Gutierrez
replace `*  * ` by `* `

2022-07-31 04:31 UTC, joel-costigliola commented on assertj-core/src/test/java/org/assertj/core/api/classes/ClassAssert_isNotPrimitive_Test.java
> +public class ClassAssert_isNotPrimitive_Test extends ClassAssertBaseTest {
no need for the class to be public

2022-07-31 04:31 UTC, joel-costigliola commented on assertj-core/src/test/java/org/assertj/core/api/classes/ClassAssert_isPrimitive_Test.java
> + * * Tests for <code>{@link ClassAssert#isPrimitive()} ()}</code>.
replace `*  * ` by `* `

2022-07-31 04:31 UTC, joel-costigliola commented on assertj-core/src/test/java/org/assertj/core/internal/classes/Classes_assertIsNotPrimitive_Test.java
> +  void should_fail_if_actual_has_byte_type() {
there is nothing wrong with these tests but I think it's a good fit for a parameterized test taking the list of primitive type as input, this should work: 
```java
  @ParameterizedTest
  @ValueSource(classes = { int.class, double.class }) // list all primitive classes
  void should_fail_if_actual_is_a_primitive_type(Class<?> primitiveClass) {
   //WHEN
    AssertionError assertionError = expectAssertionError(() -> assertThat(primitiveClass).isNotPrimitive());
    //THEN
    then(assertionError).hasMessage(shouldNotBePrimitive(primitiveClass).create());
  }
```
Once this is done, you can remove the other `should_fail_if_actual_has_...` tests

2022-07-31 04:31 UTC, joel-costigliola commented on assertj-core/src/test/java/org/assertj/core/internal/classes/Classes_assertIsPrimitive_Test.java
> +  void should_pass_if_actual_has_byte_type() {
use a parameterized tests similar to the one I suggested in `Classes_assertIsNotPrimitive_Test`

2022-07-31 09:57 UTC, joel-costigliola commented on assertj-core/src/test/java/org/assertj/core/api/classes/ClassAssert_isNotPrimitive_Test.java
> +package org.assertj.core.api.classes;
add the javadoc comment with the licence, this is why the build failed.
add it to every new files

2022-07-31 09:58 UTC, joel-costigliola commented on assertj-core/src/main/java/org/assertj/core/error/ShouldBePrimitive.java
> +package org.assertj.core.error;
add javadoc licence

2022-08-01 14:26 UTC, ManuelG28 commented
Hi, @joel-costigliola thanks for the information about `@ParameterizedTest`. 
I have learned something new today!

Please let me know if I need to change something else.

2023-09-30 22:14 UTC, closed without merging

2023-09-30 22:14 UTC, joel-costigliola commented
Integrated thanks @ManuelG28 !