Feature/2697 assertion failed error
assertj/assertj pull request #2824
Opened 2022-10-27 13:42 UTC by ChrisZoet

#### Check List:
* Fixes #??? (ignore if not applicable)
* Unit tests :  NA
* Javadoc with a code example (on API only) :  NA
* PR meets the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md)

Following the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md) will make it easier for us to review and accept your  #PR.

**Changes:**

Calling a new failure method inside Iterables that eventually invokes assertionFailedError from AssertionErrorCreator with the expected and actual values needed for the <Click to see difference> feature when AssertionFailedError is thrown. 

Also made modifications on Iterables_assertContainsExactly_tests to call the same failure method.

--------------------------------------------------------------------------------------------------------------------------------------------

**Results**

**Old:**

![image](https://user-images.githubusercontent.com/113503359/198300776-927418dd-c87c-4695-a880-3a5dedde2afb.png)

**New:**

![image](https://user-images.githubusercontent.com/113503359/198299596-58c647a2-5dce-412d-ad27-25ce1ec84b9e.png)

2022-10-30 04:15 UTC, joel-costigliola requested changes
@ChrisZoet thanks for the PR, it looks good.
You have done the changes for iterables, we should also do them for arrays in https://github.com/assertj/assertj/blob/main/assertj-core/src/main/java/org/assertj/core/internal/Arrays.java#L276

2022-10-30 04:15 UTC, joel-costigliola commented on assertj-core/src/main/java/org/assertj/core/internal/Iterables.java
> +                                                                                 List<IndexedDiff> indexedDiffs, AssertionInfo info) {
minor: keep original formatting

2022-11-02 07:57 UTC, ChrisZoet commented
> @ChrisZoet thanks for the PR, it looks good. You have done the changes for iterables, can you also do them for arrays in https://github.com/assertj/assertj/blob/main/assertj-core/src/main/java/org/assertj/core/internal/Arrays.java#L276, thanks!

Will do!

2022-11-05 05:11 UTC, joel-costigliola commented
Integrated thanks @ChrisZoet for the good work!

2022-11-05 05:11 UTC, closed without merging