Provide value when assertThatThrownBy fails
assertj/assertj pull request #3044
Opened 2023-05-14 10:06 UTC by findepi

#### Check List:
* Fixes https://github.com/assertj/assertj/issues/3043
* Unit tests : YES
* Javadoc with a code example (on API only) : NO, not yet
* PR meets the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md) -- i hope so!

Following the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md) will make it easier for us to review and accept your PR.

2023-05-14 10:08 UTC, findepi commented on assertj-core/src/main/java/org/assertj/core/api/Assertions.java
> +  }
I am pretty sure that this is not how it should eventually look like.
Very minimum would be a javadoc.
This is for issue illustration / POC at this stage.

Happy to improve if this is at least directionally correct.

2023-05-16 08:22 UTC, joel-costigliola commented
Thanks @findepi, I will review your PR shortly!

2023-05-16 08:24 UTC, joel-costigliola requested changes

2023-05-16 08:24 UTC, joel-costigliola commented on assertj-core/src/main/java/org/assertj/core/api/Assertions.java
> +  }
This looks good to me.

We need to do the same in BDDAssertions

2023-05-16 19:46 UTC, findepi commented
Thanks @joel-costigliola for your review!
added similar change in BDDAssertions. Also added this for overloads that take `String description, Object... args`.

2023-05-22 09:51 UTC, joel-costigliola commented
Integrated thanks @findepi!

2023-05-22 09:51 UTC, closed without merging

2023-05-22 16:46 UTC, findepi commented
thank you Joel!